version: '3.8'

services:
  frontend:
    build: ./
    ports:
      - "80:80"
    networks:
      - general

  backend:
    build: ./datagen-backend/.
    ports:
      - "3000:3000"
    networks:
      - general

networks:
  general:
